language: php

php:
  - 7.2
  - 7.3
  - 8.0
  - 8.1
  - 8.2

dist: trusty

before_install:
  - pear config-set preferred_state beta
  - pecl channel-update pecl.php.net
  - yes | pecl install imagick

install:
  - composer self-update
  - composer install

script:
  - vendor/bin/phpunit
